server:
  port: 9002

eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://127.0.0.1:${server.port}/info
    healthCheckUrl: https://127.0.0.1:${server.port}/actuator/health
    secureHealthCheckUrl: https://127.0.0.1:${server.port}/actuator/health
    homePageUrl: https://127.0.0.1:${server.port}
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: https://admin:admin@127.0.0.1:8762/eureka,https://admin:admin@localhost:8761/eureka
