

spring:
  application:
    name: Dummy


server:
  ssl:
    enabled: true
    client-auth: WANT
    key-store: D:\dev\workspace\eureka-ssl\Disc-ssl\Disc-ssl\src\main\resources\to.jks
    key-store-password: chase123
    trust-store: D:\dev\workspace\eureka-ssl\Disc-ssl\Disc-ssl\src\main\resources\from.jks
    trust-store-password: chase123
    key-password: chase123
    key-alias: to
#  port: 8001

