server:
  port: 9001

eureka:
  instance:
#    nonSecurePortEnabled: false
#    securePortEnabled: true
#    securePort: ${server.port}
#    statusPageUrl: https://localhost:${server.port}/info
#    healthCheckUrl: https://localhost:${server.port}/actuator/health
#    secureHealthCheckUrl: https://localhost:${server.port}/actuator/health
#    homePageUrl: https://localhost:${server.port}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://127.0.0.1:8762/eureka
